Repository bank-vaults/secrets-webhook, pull requests merged in 2024-06, with the labels that each got.

#74 fix: typos in issue template
  .github/ISSUE_TEMPLATE/bug_report.yaml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.yaml
Labels: size/S, kind/cleanup

#79 chore: bump go version 1.22.2 --> 1.22.3
  go.mod
Labels: size/XS

#81 chore: prepare for v0.1.0 release
  .github/workflows/ci.yaml
  deploy/charts/secrets-webhook/README.md
  deploy/charts/secrets-webhook/values.yaml
  garden.yaml
  go.mod
  go.sum
  pkg/provider/bao/configmap.go
  pkg/provider/bao/object.go
  pkg/provider/bao/pod.go
  pkg/provider/bao/secret.go
  pkg/provider/common/pod.go
  pkg/provider/vault/configmap.go
  pkg/provider/vault/object.go
  pkg/provider/vault/pod.go
  pkg/provider/vault/secret.go
Labels: size/S, area/build

#82 feat(build): add image signing GH action
  .github/workflows/artifacts.yaml
Labels: size/S, area/pipeline, area/build, area/security, area/artifacts

#91 feat: support _json_key when mutating docker credentials
  pkg/provider/bao/secret.go
  pkg/provider/common/secret.go
  pkg/provider/vault/secret.go
Labels: size/M, kind/feature

#83 chore: post release cleanup
  .github/workflows/ci.yaml
  .yamlignore
  .yamllint.yaml
  e2e/main_test.go
  garden.yaml
  project.garden.yaml
Labels: size/S
